@startuml 02-caso-uso-cancelar-reprogramar-turno
left to right direction
skinparam packageStyle rectangle

actor "Secretaria" as sec
actor "Paciente" as pac

rectangle "Sistema de Turnos Médicos" {
  usecase "Cancelar turno" as UC1
  usecase "Reprogramar turno" as UC2
  usecase "Buscar turno existente" as UC3
  usecase "Enviar notificación de cancelación" as UC4
  usecase "Registrar nuevo turno" as UC5

  UC1 ..> UC3 : <<include>>
  UC1 ..> UC4 : <<include>>
  UC2 ..> UC3 : <<include>>
  UC2 ..> UC5 : <<include>>
  UC2 ..> UC4 : <<include>>
}

sec --> UC1
sec --> UC2
pac --> UC1
pac --> UC2
@enduml
